In [12]:
import numpy as np
from datetime import date, timedelta

### 1. Create a 3x3x3 array with random values

In [4]:
a = np.random.rand(3,3,3)
a

array([[[0.32181588, 0.88443529, 0.50894239],
        [0.1576961 , 0.30952451, 0.9416243 ],
        [0.23469613, 0.78144051, 0.43628691]],

       [[0.22523057, 0.30396066, 0.23778176],
        [0.09920277, 0.53170704, 0.39021278],
        [0.64966282, 0.67054689, 0.48977284]],

       [[0.26899595, 0.78805521, 0.45349245],
        [0.77222299, 0.92154522, 0.88419249],
        [0.60530302, 0.05795234, 0.8232349 ]]])

### 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
b = np.diag(np.arange(4) + 1, k = -1)
b


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 3. Create a 8x8 matrix and fill it with a checkerboard pattern¶

In [7]:
c = np.tile(np.array([[0,1],[1,0]]), (4,4))
c

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 4. Normalize a 5x5 random matrix

In [9]:
d = np.random.random((5,5))
d = (d - np.mean (d)) / (np.std (d))
d

array([[-0.5451553 , -1.33760921,  0.15680654, -0.13559237,  1.68437002],
       [-1.46467056,  0.04740066,  1.27371224, -1.17397403,  0.2519487 ],
       [ 0.93989198,  0.78336001, -0.39664143, -1.31391893,  0.64287163],
       [ 1.67171907,  0.50164041, -0.90665611, -1.36868997, -1.08161862],
       [ 0.99545633, -0.09426637,  0.52962367,  1.34861907, -1.00862743]])

### 5. How to find common values between two arrays

In [11]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)

a3 = np.intersect1d(a1, a2)
a3

array([2, 3, 4, 7, 9])

### 6. How to get the dates of yesterday, today and tomorrow?

In [13]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-07-31 2020-08-01 2020-08-02


### 7. Consider two random array A and B, check if they are equal

In [16]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
arr1

array([[0.79105934, 0.78658228, 0.43129902],
       [0.21759651, 0.85149169, 0.42969442],
       [0.35214321, 0.55061001, 0.77076627]])

In [17]:
arr2

array([[0.57645862, 0.69672426, 0.53135152],
       [0.13219634, 0.24056131, 0.12678787],
       [0.78612184, 0.86271481, 0.54342276]])

In [18]:
arr1 == arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### 8. Create random vector of size 10 and replace the maximum value by 0

In [19]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.91630343, 0.77473891, 0.13274855, 0.10488942, 0.18602955,
       0.        , 0.19700216, 0.47514252, 0.90976744, 0.88375862])

### 9. How to print all the values of an array?

In [35]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 10. Subtract the mean of each row of a matrix

In [26]:
sub = np.random.rand(3,3)
sub_arr_mean = sub - sub.mean(axis=1, keepdims=True)

sub_arr_mean

array([[-0.11542202, -0.22160366,  0.33702568],
       [-0.31052466, -0.00673289,  0.31725754],
       [-0.15809864,  0.46562885, -0.30753021]])

### 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?¶

In [27]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([3., 4., 1., 2., 5.])

### 12. How to get the diagonal of a dot product?

In [28]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([69, 87, 77])

### 13. How to find the most frequent value in an array?

In [29]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[1 8 5 5 1 3 5 2 7 5 9 1 3 2 0 8 7 2 1 5]


5

### 14. How to get the n largest values of an array

In [30]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

4

### 15. How to create a record array from a regular array?

In [36]:
arr = np.array([("A", 88.5, 90),
                 ("B", 87, 99),
             ("C", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['A' '88.5' '90']
 ['B' '87' '99']
 ['C' '85.5' '91']]

RECORD ARRAY


rec.array([(b'A', 88.5, 90), (b'B', 87. , 99), (b'C', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])