In [37]:
from sklearn import neighbors
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn import svm

In [2]:
df = pd.read_csv("train (1).csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# KNN

In [15]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked'],
      dtype='object')

In [16]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df["Sex"])
df['Embarked'] = le.fit_transform(df["Embarked"])

In [18]:
X = df.drop(["PassengerId", "Pclass"], axis=1)
y = df["Pclass"]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [30]:
acc_scores = dict()
def KNN(k):
    print(f"\t\t K= {k}")
    knn = neighbors.KNeighborsClassifier(n_neighbors = k)
    print(f"Accuracy score based on k = {k} using score() \n{round(knn.fit(X_train,y_train).score(X_test,y_test)*100,4)}\n")

    pred = knn.predict(X_test)
    
    
    acc_score = round(accuracy_score(y_test, pred, normalize=True)*100,4)
    print(f"Accuracy score using accuracy_score() \n{acc_score}\n")
    
    conf = confusion_matrix(y_test, pred)
    lr  = conf[0, 0] + conf[1, 1]
    rl = conf[0, 1] + conf[1, 0]
#     conf_matrix_acc=round((lr/(lr+rl))*100,4)
#     print(f"Accuracy score using accuracy_score() \n{round(conf_matrix_acc*100,4)}")
    print(f"Confusion Matrix: \n{conf}")
    
    acc_scores[k] = acc_score

    
    print("*************************************************************************************")

In [31]:
for x in range(1, 623):
    KNN(x)

		 K= 1
Accuracy score based on k = 1 using score() 
89.1386

Accuracy score using accuracy_score() 
89.1386

Confusion Matrix: 
[[ 62   6   2]
 [  3  37   9]
 [  1   8 139]]
*************************************************************************************
		 K= 2
Accuracy score based on k = 2 using score() 
86.5169

Accuracy score using accuracy_score() 
86.5169

Confusion Matrix: 
[[ 67   2   1]
 [  8  37   4]
 [  4  17 127]]
*************************************************************************************
		 K= 3
Accuracy score based on k = 3 using score() 
86.5169

Accuracy score using accuracy_score() 
86.5169

Confusion Matrix: 
[[ 63   5   2]
 [  7  28  14]
 [  3   5 140]]
*************************************************************************************
		 K= 4
Accuracy score based on k = 4 using score() 
82.397

Accuracy score using accuracy_score() 
82.397

Confusion Matrix: 
[[ 61   7   2]
 [  8  30  11]
 [  4  15 129]]
********************************************

Accuracy score using accuracy_score() 
77.9026

Confusion Matrix: 
[[ 62   5   3]
 [  7  22  20]
 [ 10  14 124]]
*************************************************************************************
		 K= 36
Accuracy score based on k = 36 using score() 
78.2772

Accuracy score using accuracy_score() 
78.2772

Confusion Matrix: 
[[ 62   5   3]
 [  7  23  19]
 [ 10  14 124]]
*************************************************************************************
		 K= 37
Accuracy score based on k = 37 using score() 
78.6517

Accuracy score using accuracy_score() 
78.6517

Confusion Matrix: 
[[ 62   5   3]
 [  7  22  20]
 [  9  13 126]]
*************************************************************************************
		 K= 38
Accuracy score based on k = 38 using score() 
79.0262

Accuracy score using accuracy_score() 
79.0262

Confusion Matrix: 
[[ 62   5   3]
 [  7  23  19]
 [  9  13 126]]
*************************************************************************************
		 K= 39
Acc


Accuracy score using accuracy_score() 
76.03

Confusion Matrix: 
[[ 57   6   7]
 [  5  11  33]
 [  5   8 135]]
*************************************************************************************
		 K= 68
Accuracy score based on k = 68 using score() 
76.03

Accuracy score using accuracy_score() 
76.03

Confusion Matrix: 
[[ 57   6   7]
 [  5  11  33]
 [  5   8 135]]
*************************************************************************************
		 K= 69
Accuracy score based on k = 69 using score() 
76.4045

Accuracy score using accuracy_score() 
76.4045

Confusion Matrix: 
[[ 56   7   7]
 [  5  11  33]
 [  5   6 137]]
*************************************************************************************
		 K= 70
Accuracy score based on k = 70 using score() 
76.4045

Accuracy score using accuracy_score() 
76.4045

Confusion Matrix: 
[[ 57   6   7]
 [  5  11  33]
 [  5   7 136]]
*************************************************************************************
		 K= 71
Accuracy

Confusion Matrix: 
[[ 53   6  11]
 [  5  10  34]
 [  5   9 134]]
*************************************************************************************
		 K= 101
Accuracy score based on k = 101 using score() 
73.0337

Accuracy score using accuracy_score() 
73.0337

Confusion Matrix: 
[[ 53   6  11]
 [  5  10  34]
 [  5  11 132]]
*************************************************************************************
		 K= 102
Accuracy score based on k = 102 using score() 
73.0337

Accuracy score using accuracy_score() 
73.0337

Confusion Matrix: 
[[ 53   5  12]
 [  5  10  34]
 [  5  11 132]]
*************************************************************************************
		 K= 103
Accuracy score based on k = 103 using score() 
73.4082

Accuracy score using accuracy_score() 
73.4082

Confusion Matrix: 
[[ 53   7  10]
 [  6  10  33]
 [  5  10 133]]
*************************************************************************************
		 K= 104
Accuracy score based on k = 104 using score(

Accuracy score using accuracy_score() 
76.03

Confusion Matrix: 
[[ 53  13   4]
 [  5  11  33]
 [  5   4 139]]
*************************************************************************************
		 K= 133
Accuracy score based on k = 133 using score() 
76.03

Accuracy score using accuracy_score() 
76.03

Confusion Matrix: 
[[ 53  13   4]
 [  5  11  33]
 [  5   4 139]]
*************************************************************************************
		 K= 134
Accuracy score based on k = 134 using score() 
75.6554

Accuracy score using accuracy_score() 
75.6554

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   4 139]]
*************************************************************************************
		 K= 135
Accuracy score based on k = 135 using score() 
76.03

Accuracy score using accuracy_score() 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
		 K= 136
Accura


Accuracy score using accuracy_score() 
75.2809

Confusion Matrix: 
[[ 52   9   9]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
		 K= 165
Accuracy score based on k = 165 using score() 
75.2809

Accuracy score using accuracy_score() 
75.2809

Confusion Matrix: 
[[ 52   9   9]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
		 K= 166
Accuracy score based on k = 166 using score() 
75.2809

Accuracy score using accuracy_score() 
75.2809

Confusion Matrix: 
[[ 52   8  10]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
		 K= 167
Accuracy score based on k = 167 using score() 
75.2809

Accuracy score using accuracy_score() 
75.2809

Confusion Matrix: 
[[ 52   7  11]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
		 K=

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   7  15]
 [  5   2  42]
 [  5   0 143]]
*************************************************************************************
		 K= 197
Accuracy score based on k = 197 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   7  15]
 [  5   2  42]
 [  5   0 143]]
*************************************************************************************
		 K= 198
Accuracy score based on k = 198 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   7  15]
 [  5   2  42]
 [  5   0 143]]
*************************************************************************************
		 K= 199
Accuracy score based on k = 199 using score() 
71.9101

Accuracy score using accuracy_score() 
71.9101

Confusion Matrix: 
[[ 48   7  15]
 [  5   1  43]
 [  5   0 143]]
*************************************************************************************
		 K= 

Accuracy score based on k = 229 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
		 K= 230
Accuracy score based on k = 230 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   1  21]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
		 K= 231
Accuracy score based on k = 231 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   0  22]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
		 K= 232
Accuracy score based on k = 232 using score() 
72.2846

Accuracy score using accuracy_score() 
72.2846

Confusion Matrix: 
[[ 48   0  22]
 [  4   2  43]
 [  5   0 143]]
************************************


Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
		 K= 262
Accuracy score based on k = 262 using score() 
71.9101

Accuracy score using accuracy_score() 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
		 K= 263
Accuracy score based on k = 263 using score() 
71.9101

Accuracy score using accuracy_score() 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
		 K= 264
Accuracy score based on k = 264 using score() 
71.9101

Accuracy score using accuracy_score() 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
		 K= 265
Accuracy score based on k = 265 using score


Confusion Matrix: 
[[ 46   0  24]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
		 K= 294
Accuracy score based on k = 294 using score() 
70.7865

Accuracy score using accuracy_score() 
70.7865

Confusion Matrix: 
[[ 46   0  24]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
		 K= 295
Accuracy score based on k = 295 using score() 
70.7865

Accuracy score using accuracy_score() 
70.7865

Confusion Matrix: 
[[ 46   0  24]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
		 K= 296
Accuracy score based on k = 296 using score() 
70.7865

Accuracy score using accuracy_score() 
70.7865

Confusion Matrix: 
[[ 46   0  24]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
		 K= 297
Accuracy score based on k = 297 using score

Accuracy score based on k = 326 using score() 
68.9139

Accuracy score using accuracy_score() 
68.9139

Confusion Matrix: 
[[ 39   4  27]
 [  3   0  46]
 [  2   1 145]]
*************************************************************************************
		 K= 327
Accuracy score based on k = 327 using score() 
68.5393

Accuracy score using accuracy_score() 
68.5393

Confusion Matrix: 
[[ 38   5  27]
 [  3   0  46]
 [  2   1 145]]
*************************************************************************************
		 K= 328
Accuracy score based on k = 328 using score() 
68.9139

Accuracy score using accuracy_score() 
68.9139

Confusion Matrix: 
[[ 39   5  26]
 [  3   0  46]
 [  2   1 145]]
*************************************************************************************
		 K= 329
Accuracy score based on k = 329 using score() 
68.9139

Accuracy score using accuracy_score() 
68.9139

Confusion Matrix: 
[[ 39   5  26]
 [  3   0  46]
 [  2   1 145]]
************************************

Accuracy score using accuracy_score() 
65.9176

Confusion Matrix: 
[[ 27   1  42]
 [  0   1  48]
 [  0   0 148]]
*************************************************************************************
		 K= 358
Accuracy score based on k = 358 using score() 
65.5431

Accuracy score using accuracy_score() 
65.5431

Confusion Matrix: 
[[ 26   1  43]
 [  0   1  48]
 [  0   0 148]]
*************************************************************************************
		 K= 359
Accuracy score based on k = 359 using score() 
65.1685

Accuracy score using accuracy_score() 
65.1685

Confusion Matrix: 
[[ 25   1  44]
 [  0   1  48]
 [  0   0 148]]
*************************************************************************************
		 K= 360
Accuracy score based on k = 360 using score() 
65.1685

Accuracy score using accuracy_score() 
65.1685

Confusion Matrix: 
[[ 25   1  44]
 [  0   1  48]
 [  0   0 148]]
*************************************************************************************
		 K= 


Accuracy score using accuracy_score() 
60.6742

Confusion Matrix: 
[[ 14   0  56]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 390
Accuracy score based on k = 390 using score() 
60.6742

Accuracy score using accuracy_score() 
60.6742

Confusion Matrix: 
[[ 14   0  56]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 391
Accuracy score based on k = 391 using score() 
60.6742

Accuracy score using accuracy_score() 
60.6742

Confusion Matrix: 
[[ 14   0  56]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 392
Accuracy score based on k = 392 using score() 
60.6742

Accuracy score using accuracy_score() 
60.6742

Confusion Matrix: 
[[ 14   0  56]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K=

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 422
Accuracy score based on k = 422 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 423
Accuracy score based on k = 423 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 424
Accuracy score based on k = 424 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 425
Accuracy score based on k = 425 using score(


Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 453
Accuracy score based on k = 453 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 454
Accuracy score based on k = 454 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 455
Accuracy score based on k = 455 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 456
Accuracy score based on k = 456 using score

Accuracy score based on k = 485 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 486
Accuracy score based on k = 486 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 487
Accuracy score based on k = 487 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 488
Accuracy score based on k = 488 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
************************************

Accuracy score based on k = 517 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 518
Accuracy score based on k = 518 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 519
Accuracy score based on k = 519 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 520
Accuracy score based on k = 520 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
************************************


Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 549
Accuracy score based on k = 549 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 550
Accuracy score based on k = 550 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 551
Accuracy score based on k = 551 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K=

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 581
Accuracy score based on k = 581 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 582
Accuracy score based on k = 582 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 583
Accuracy score based on k = 583 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 


Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 613
Accuracy score based on k = 613 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 614
Accuracy score based on k = 614 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 615
Accuracy score based on k = 615 using score() 
55.4307

Accuracy score using accuracy_score() 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
		 K= 616
Accuracy score based on k = 616 using score

In [32]:
scores = acc_scores.values()
ks = acc_scores.keys()

max_score = max(scores)
max_k = list(ks)[list(scores).index(max_score)]

max_k, max_score

(1, 89.1386)

# SVM

In [33]:
clf = svm.SVC(gamma = 0.01, C = 100)
def SVM(x, y):
    X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state = 0)
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    acc = round(accuracy_score(y_test, y_pred, normalize = True) * 100, 2)
    confm = confusion_matrix(y_test, y_pred)
    return [acc, confm]

In [34]:
df = df.drop(['PassengerId'], axis = 1)

In [35]:
models = []
for enum, i in enumerate(df.columns):
    if i == 'Age' or i == 'Fare':
        continue
    y = df.iloc[:, enum:enum+1]
    x = df.drop(columns = y.columns)
    models.append([SVM(x, y), y.columns[0]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [38]:
for _ in models:
    print(f'{_[1]} vs {str(df.drop([_[1]], axis=1).columns.to_list()).strip("[]")}\n')
    print(f'Accuracy: {_[0][0]}')
    print(f'Confusion Matrix: \n {_[0][1]}\n')
    print(f"Out of total 267 records only {np.trace(_[0][1])} are successfully classified, giving a model accuracy of {_[0][0]}%.")
    print('\n-----------------------\n')

Survived vs 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 74.16
Confusion Matrix: 
 [[124  33]
 [ 36  74]]

Out of total 267 records only 198 are successfully classified, giving a model accuracy of 74.16%.

-----------------------

Pclass vs 'Survived', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 90.26
Confusion Matrix: 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]

Out of total 267 records only 241 are successfully classified, giving a model accuracy of 90.26%.

-----------------------

Sex vs 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 72.66
Confusion Matrix: 
 [[ 66  32]
 [ 41 128]]

Out of total 267 records only 194 are successfully classified, giving a model accuracy of 72.66%.

-----------------------

SibSp vs 'Survived', 'Pclass', 'Sex', 'Age', 'Parch', 'Fare', 'Embarked'

Accuracy: 74.91
Confusion Matrix: 
 [[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
