In [52]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import *
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [36]:
df = pd.read_csv("train (1).csv")

In [37]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [38]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [39]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [43]:
df1 = df.drop(columns = ['Cabin', 'PassengerId', 'Name', 'Ticket'])
df1.dropna(inplace = True)
df1.drop_duplicates(inplace=True)

In [44]:
df1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [45]:
df1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [49]:
le =LabelEncoder()
df1["Sex"] = le.fit_transform(df1['Sex'])
df1["Embarked"] = le.fit_transform(df1["Embarked"])


In [50]:
df1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [31]:
clf= BernoulliNB()


In [41]:
def naive(X, y, rstate):
    X_train, X_test, y_train, y_test  = train_test_split(X,y,test_size=0.3,random_state=0)
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    acc = accuracy_score(y_test, y_pred, normalize=True)
    con = confusion_matrix(y_test, y_pred)
    return [acc, con]


In [51]:
rstate=-1
models =[]
for enum, i in enumerate(df1.columns[1:]):
    if i == 'Age' or i == 'Fare':
        continue
    y = df1.iloc[:, enum+1:enum+2]
    X = df1.drop(columns = y.columns)
    rstate += 1
    models.append([naive(X, y, rstate), y.columns[0]])
    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [53]:
for _ in models:
    print(f'{_[1]} vs All\n')
    print(f'Accuracy: {_[0][0]}')
    print(f'Confusion Matrix: \n {_[0][1]}\n')
    print(f"Out of total 267 records only {np.trace(_[0][1])} are successfully classified, giving a model accuracy of {int(_[0][0]*100)}%.")
    print('\n-----------------------\n')

Pclass vs All

Accuracy: 0.5622317596566524
Confusion Matrix: 
 [[ 26   3  38]
 [  5   4  44]
 [ 10   2 101]]

Out of total 267 records only 131 are successfully classified, giving a model accuracy of 56%.

-----------------------

Sex vs All

Accuracy: 0.7253218884120172
Confusion Matrix: 
 [[ 53  41]
 [ 23 116]]

Out of total 267 records only 169 are successfully classified, giving a model accuracy of 72%.

-----------------------

SibSp vs All

Accuracy: 0.6394849785407726
Confusion Matrix: 
 [[133  20   0   0   0   0]
 [ 40  16   0   0   0   0]
 [  9   2   0   0   0   0]
 [  2   3   0   0   0   0]
 [  4   2   0   0   0   0]
 [  1   1   0   0   0   0]]

Out of total 267 records only 149 are successfully classified, giving a model accuracy of 63%.

-----------------------

Parch vs All

Accuracy: 0.6952789699570815
Confusion Matrix: 
 [[156  20   0   0   0]
 [ 20   6   0   0   0]
 [ 25   3   0   0   0]
 [  0   1   0   0   0]
 [  2   0   0   0   0]]

Out of total 267 records only 162 